name: Print Hello World
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: 'echo "Hello, World!"'
      - name: Test
        run: 'echo "Hello, Test!"'
