name: Create EC2 Instance
'on':
  push:
    branches:
      - main
jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Create EC2 Instance
        run: >
          aws configure set aws_access_key_id ${{ secrets.KEY }}

          aws configure set aws_secret_access_key ${{
          secrets.KEY2 }}

          aws configure set default.region ${{ secrets.AWS_REGION }}

          aws ec2 run-instances --image-id ami-12345678 --instance-type t2.micro
          --key-name my-keypair --tag-specifications
          'ResourceType=instance,Tags=[{Key=Name,Value=MyInstance}]'
